apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ingress-dashboard
  labels:
    app: kube-ingress-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ingress-dashboard
  template:
    metadata:
      labels:
        app: kube-ingress-dashboard
    spec:
      containers:
        - name: kube-ingress-dashboard
          image: ghcr.io/antvirf/kube-ingress-dashboard:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 10m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kube-ingress-dashboard
  labels:
    app: kube-ingress-dashboard
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kube-ingress-dashboard
